export const pokemonGenerations = {
  1: "Generation I",
  2: "Generation II",
  3: "Generation III",
  4: "Generation IV",
  5: "Generation V",
  6: "Generation VI",
  7: "Generation VII",
  8: "Generation VIII",
};

export const pokemonTypes = {
  normal: {bgColor: "bg-gray-500"},
  fighting: {bgColor: "bg-yellow-700"},
  flying: {bgColor: "bg-yellow-500"},
  poison: {bgColor: "bg-purple-600"},
  ground: {bgColor: "bg-yellow-800"},
  rock: {bgColor: "bg-amber-800"},
  bug: {bgColor: "bg-green-600"},
  ghost: {bgColor: "bg-pink-800"},
  steel: {bgColor: "bg-gray-700"},
  fire: {bgColor: "bg-red-600"},
  water: {bgColor: "bg-blue-500"},
  grass: {bgColor: "bg-green-600"},
  electric: {bgColor: "bg-yellow-500"},
  psychic: {bgColor: "bg-purple-800"},
  ice: {bgColor: "bg-blue-400"},
  dragon: {bgColor: "bg-orange-500"},
  dark: {bgColor: "bg-purple-700"},
  fairy: {bgColor: "bg-pink-500"},
}