export const typeColors = {
  fire: "bg-red-600",
  grass: "bg-green-600",
  poison: "bg-purple-600",
  bug: "bg-green-600",
  flying: "bg-yellow-600",
  water: "bg-blue-600",
  normal: "bg-gray-600",
  rock: "bg-amber-600",
  electric: "bg-yellow-600",
  ice: "bg-blue-500",
  fairy: "bg-pink-500",
  psychic: "bg-purple-500",
  ground: "bg-amber-600",
  fighting: "bg-yellow-700",
  dragon: "bg-red-800",
  dark: "bg-purple-700",
  ghost: "bg-purple-500",
  steel: "bg-gray-500",
};

export const generations = {
  1: "Generation I",
  2: "Generation II",
  3: "Generation III",
  4: "Generation IV",
  5: "Generation V",
  6: "Generation VI",
  7: "Generation VII",
  8: "Generation VIII",
};

export const types = {
  1: "normal",
  2: "fighting",
  3: "flying",
  4: "poison",
  5: "ground",
  6: "rock",
  7: "bug",
  8: "ghost",
  9: "steel",
  10: "fire",
  11: "water",
  12: "grass",
  13: "electric",
  14: "psychic",
  15: "ice",
  16: "dragon",
  17: "dark",
  18: "fairy",
  19: "unknown",
  20: "shadow",
}